import './theme.css'

import './source/omni-oscillator'
import './source/oscillator'
import './source/player'
import './source/noise'
import './source/microphone'
import './source/grain-player'

import './input/slider'
import './input/multislider'
import './input/keyboard'
import './input/piano'
import './input/trigger'

import './instrument/synth'
import './instrument/mono-synth'
import './instrument/metal-synth'
import './instrument/membrane-synth'
import './instrument/noise-synth'
import './instrument/fm-synth'

import './component/filter'
import './component/envelope'
import './component/pan-vol'

import './page/unmute'
import './page/topbar'
import './page/content'
import './page/drawer'
import './page/explanation'
import './page/loader'

import './viz/oscilloscope'
import './viz/fft'

import './effect/chorus'
import './effect/chebychev'
import './effect/freeverb'
import './effect/tremolo'
import './effect/auto-filter'
import './effect/auto-panner'
